language: php
php:
  - '7.2.22'
  - '7.3.23'
  - '7.4.15'
before_script:
  - mkdir -p /home/travis/build/drosanda/seme-framework/app/cache/
  - chmod 775 /home/travis/build/drosanda/seme-framework/app/cache/
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS seme_framework;'
  - sudo mysql -u root --default-character-set=utf8 seme_framework < sql/seme_framework.sql
after_success:
    - bash <(curl -s https://codecov.io/bash)
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - phpunit --configuration phpunit.xml --coverage-clover coverage.xml --log-junit junit.xml --testsuite Dev
addons:
  mariadb: '10.3'
